(function () {
  window.KAUJUN_PRODUCTS = [
    {
      "id": "s072-clip-light-basic",
      "title": "クリップ式 LED デスクライト 省スペース",
      "description": "机が狭い人向けのクリップ式ライト候補。購入前に天板の厚み、固定位置、給電場所を確認してください。",
      "imageUrl": "./product-placeholder.svg",
      "affiliateUrl": "https://hb.afl.rakuten.co.jp/hgc/g00sl7wn.k9qwp74e.g00sl7wn.k9qwqcc8/?pc=https%3A%2F%2Fitem.rakuten.co.jp%2Fhotprice%2Fmot04678%2F&m=http%3A%2F%2Fm.rakuten.co.jp%2Fhotprice%2Fi%2F10005022%2F&rafcid=wsc_i_is_cfffb985-e82f-4439-9947-c9a1499a5f56",
      "merchant": "ほっとプライス 楽天市場店",
      "category": "デスクライト",
      "shortTitle": "クリップ式デスクライト、買う前にこの3つだけ見て #Shorts",
      "shortUrl": "https://www.youtube.com/watch?v=cLeo3SzwjYw",
      "isPr": true,
      "priority": 100,
      "updatedAt": "2026-06-30"
    },
    {
      "id": "s072-clip-light-review",
      "title": "クリップライト 調光・調色 レビュー多め",
      "description": "調光、調色、レビュー数を見ながら比較したい人向けの候補。設置場所とアームの保持力を先に確認してください。",
      "imageUrl": "./product-placeholder.svg",
      "affiliateUrl": "https://hb.afl.rakuten.co.jp/hgc/g00syo5n.k9qwp6b4.g00syo5n.k9qwqe8e/?pc=https%3A%2F%2Fitem.rakuten.co.jp%2Fshopapalus%2Ftd-3w-1%2F&m=http%3A%2F%2Fm.rakuten.co.jp%2Fshopapalus%2Fi%2F10000025%2F&rafcid=wsc_i_is_cfffb985-e82f-4439-9947-c9a1499a5f56",
      "merchant": "Ankoo",
      "category": "デスクライト",
      "shortTitle": "クリップ式デスクライト、買う前にこの3つだけ見て #Shorts",
      "shortUrl": "https://www.youtube.com/watch?v=cLeo3SzwjYw",
      "isPr": true,
      "priority": 95,
      "updatedAt": "2026-06-30"
    },
    {
      "id": "s072-arm-clip-light",
      "title": "アーム式 クリップ デスクライト 角度調整",
      "description": "手元作業で照らす位置を変えたい人向けの候補。関節部分の可動域と、毎回ずれにくいかを確認してください。",
      "imageUrl": "./product-placeholder.svg",
      "affiliateUrl": "https://hb.afl.rakuten.co.jp/hgc/g00syo5n.k9qwp6b4.g00syo5n.k9qwqe8e/?pc=https%3A%2F%2Fitem.rakuten.co.jp%2Fshopapalus%2Fdesk-light-04%2F&m=http%3A%2F%2Fm.rakuten.co.jp%2Fshopapalus%2Fi%2F10000543%2F&rafcid=wsc_i_is_cfffb985-e82f-4439-9947-c9a1499a5f56",
      "merchant": "Ankoo",
      "category": "デスクライト",
      "shortTitle": "クリップ式デスクライト、買う前にこの3つだけ見て #Shorts",
      "shortUrl": "https://www.youtube.com/watch?v=cLeo3SzwjYw",
      "isPr": true,
      "priority": 90,
      "updatedAt": "2026-06-30"
    },
    {
      "id": "s071-stand-light",
      "title": "LED デスクライト 調光・調色",
      "description": "読書や作業用に標準的なスタンド式を検討する人向けの候補。台座サイズと手元の影を確認してください。",
      "imageUrl": "./product-placeholder.svg",
      "affiliateUrl": "https://hb.afl.rakuten.co.jp/hgc/g00t17vn.k9qwpd25.g00t17vn.k9qwq92f/?pc=https%3A%2F%2Fitem.rakuten.co.jp%2Filemon%2Fmjd1006%2F&m=http%3A%2F%2Fm.rakuten.co.jp%2Filemon%2Fi%2F10000111%2F&rafcid=wsc_i_is_cfffb985-e82f-4439-9947-c9a1499a5f56",
      "merchant": "ilemon",
      "category": "デスクライト",
      "shortTitle": "デスクライト、買う前にこの3つだけ見て #Shorts",
      "shortUrl": "https://www.youtube.com/watch?v=gFRPB7CyreU",
      "isPr": true,
      "priority": 82,
      "updatedAt": "2026-06-30"
    },
    {
      "id": "s068-wayetto-monitor-light",
      "title": "WAYETTO モニターライト",
      "description": "モニター上に設置するライト候補。モニターの厚み、曲面形状、手元の照らし方を確認してください。",
      "imageUrl": "./product-placeholder.svg",
      "affiliateUrl": "https://hb.afl.rakuten.co.jp/hgc/g00u9gun.k9qwpbb5.g00u9gun.k9qwqa17/?pc=https%3A%2F%2Fitem.rakuten.co.jp%2Fwayetto%2Fwtdl0030%2F&m=http%3A%2F%2Fm.rakuten.co.jp%2Fwayetto%2Fi%2F10000388%2F&rafcid=wsc_i_is_cfffb985-e82f-4439-9947-c9a1499a5f56",
      "merchant": "WAYetTO",
      "category": "モニターライト",
      "shortTitle": "モニターライト、買う前にこの3つだけ見て #Shorts",
      "shortUrl": "https://www.youtube.com/watch?v=9GkA-fnYZUA",
      "isPr": true,
      "priority": 78,
      "updatedAt": "2026-06-23"
    },
    {
      "id": "s068-benq-screenbar",
      "title": "BenQ ScreenBar モニターライト",
      "description": "モニターライトをしっかり比較したい人向けの候補。価格だけでなく、自動調光や設置条件を確認してください。",
      "imageUrl": "./product-placeholder.svg",
      "affiliateUrl": "https://hb.afl.rakuten.co.jp/hgc/g00tkdfn.k9qwp815.g00tkdfn.k9qwq946/?pc=https%3A%2F%2Fitem.rakuten.co.jp%2Fbenq-directshop%2Flighting-screenbar-pro%2F&m=http%3A%2F%2Fm.rakuten.co.jp%2Fbenq-directshop%2Fi%2F10000421%2F&rafcid=wsc_i_is_cfffb985-e82f-4439-9947-c9a1499a5f56",
      "merchant": "ベンキューダイレクト楽天市場店",
      "category": "モニターライト",
      "shortTitle": "モニターライト、買う前にこの3つだけ見て #Shorts",
      "shortUrl": "https://www.youtube.com/watch?v=9GkA-fnYZUA",
      "isPr": true,
      "priority": 74,
      "updatedAt": "2026-06-23"
    },
    {
      "id": "s069-anker-cable-holder",
      "title": "Anker Magnetic Cable Holder",
      "description": "デスク上のケーブルを戻しやすくしたい人向けの候補。粘着面、設置位置、ケーブル径を確認してください。",
      "imageUrl": "./product-placeholder.svg",
      "affiliateUrl": "https://hb.afl.rakuten.co.jp/hgc/g00rr09n.k9qwp9f6.g00rr09n.k9qwq1c2/?pc=https%3A%2F%2Fitem.rakuten.co.jp%2Fanker%2Fa8891%2F&m=http%3A%2F%2Fm.rakuten.co.jp%2Fanker%2Fi%2F10000881%2F&rafcid=wsc_i_is_cfffb985-e82f-4439-9947-c9a1499a5f56",
      "merchant": "アンカー・ダイレクト楽天市場店",
      "category": "ケーブル整理",
      "shortTitle": "買う前に見て。AIが選んだ後悔しやすいデスク用品 #Shorts",
      "shortUrl": "https://www.youtube.com/watch?v=nbT1nysOhpA",
      "isPr": true,
      "priority": 68,
      "updatedAt": "2026-06-23"
    },
    {
      "id": "s069-logicool-m750",
      "title": "Logicool Signature M750",
      "description": "ワイヤレスマウスを検討する人向けの候補。手のサイズ、静音性、接続方式を確認してください。",
      "imageUrl": "./product-placeholder.svg",
      "affiliateUrl": "https://hb.afl.rakuten.co.jp/hgc/g00tpxdn.k9qwp262.g00tpxdn.k9qwqa61/?pc=https%3A%2F%2Fitem.rakuten.co.jp%2Flogicool%2Fm750mgr%2F&m=http%3A%2F%2Fm.rakuten.co.jp%2Flogicool%2Fi%2F10000503%2F&rafcid=wsc_i_is_cfffb985-e82f-4439-9947-c9a1499a5f56",
      "merchant": "ロジクール 公式ストア",
      "category": "入力機器",
      "shortTitle": "買う前に見て。AIが選んだ後悔しやすいデスク用品 #Shorts",
      "shortUrl": "https://www.youtube.com/watch?v=nbT1nysOhpA",
      "isPr": true,
      "priority": 60,
      "updatedAt": "2026-06-23"
    }
  ];
}());
